import Foundation
import Testing
@testable import Panops

/// Covers `AppViewModel.handleAutoNotesAfterStop` — the post-stop branch that
/// either tracks an engine-enqueued auto-notes job through the shared working
/// flow, or surfaces a deferred hint when the engine couldn't start it.
///
/// The dummy socket path is never connected for the deferred / no-op cases. The
/// tracked case attaches a polling safety net (which would try the socket); the
/// test asserts the synchronous `.working` transition and then `reset()`s to
/// cancel that polling.
@MainActor
@Suite("Auto-generate notes after stop")
struct AutoGenerateNotesTests {
    private func makeViewModel() -> AppViewModel {
        AppViewModel(client: IpcClient(socketPath: URL(fileURLWithPath: "/tmp/panops-autonotes-test.sock")))
    }

    @Test("a stop result with a notes job id enters the tracked working flow")
    func tracksAutoGeneratedNotesJob() async {
        let vm = makeViewModel()
        let outcome = RecordingStopOutcome(
            audioURL: URL(fileURLWithPath: "/tmp/system.wav"),
            notesJobId: "auto-job-1",
            autoGenerateNotesRequested: true
        )

        await vm.handleAutoNotesAfterStop(meetingId: "m1", outcome: outcome)

        #expect(vm.deferredNotesHint == nil)
        #expect(vm.notesGenMeetingId == "m1")
        if case .working(let meetingId, let audioName) = vm.state {
            #expect(meetingId == "m1")
            #expect(audioName == "system.wav")
        } else {
            Issue.record("expected .working, got \(vm.state)")
        }

        // Cancel the polling safety net the tracked flow spawned.
        vm.reset()
    }

    @Test("auto requested but no job id surfaces a deferred hint, not an error")
    func surfacesDeferredHintWhenComputeNotReady() async {
        let vm = makeViewModel()
        let outcome = RecordingStopOutcome(
            audioURL: URL(fileURLWithPath: "/tmp/system.wav"),
            notesJobId: nil,
            autoGenerateNotesRequested: true
        )

        await vm.handleAutoNotesAfterStop(meetingId: "m1", outcome: outcome)

        #expect(vm.deferredNotesHint == AppViewModel.DeferredNotesHint(
            meetingId: "m1",
            message: AppViewModel.deferredNotesMessage
        ))
        // A gentle hint — not a working state and not an error.
        if case .working = vm.state { Issue.record("deferred hint must not enter .working") }
        if case .error = vm.state { Issue.record("deferred hint must not be an error") }
    }

    @Test("no auto request and no job id is a no-op")
    func noOpWhenAutoNotRequested() async {
        let vm = makeViewModel()
        let outcome = RecordingStopOutcome(
            audioURL: nil,
            notesJobId: nil,
            autoGenerateNotesRequested: false
        )

        await vm.handleAutoNotesAfterStop(meetingId: "m1", outcome: outcome)

        #expect(vm.deferredNotesHint == nil)
        if case .working = vm.state { Issue.record("no-op must not enter .working") }
    }
}
